FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["Backend/api.csproj", "Backend/"]
RUN dotnet restore "Backend/api.csproj"
COPY . .
WORKDIR "/src/Backend/"
RUN dotnet publish "api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 5042
ENV ASPNETCORE_URLS=http://0.0.0.0:5042
ENTRYPOINT ["dotnet", "PlataformaWebDadosUnB.dll"]
